# do not touch this line
configVersion: 2

name: intrudersDetector
description: Simple app detecting people
keywords: everloop camera face-detection

services:
  intrudersDetector:
    engine: detection
    type: demographics
